name: Sync Upstream

on:
  schedule:
    # 每小时
    - cron: '0 * * * *'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up upstream remote
        run: git remote add upstream https://github.com/imsyy/DailyHot.git

      - name: Setup Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Fetch upstream
        run: git fetch upstream

      - name: Merge upstream/main into main
        run: git merge upstream/main --allow-unrelated-histories || echo "No changes to merge"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
